### ISSUE TITLE
Slow cookie splitting

### ISSUE THREAD

**Issue by roberttod** [QubitProducts/cookieman#10]
I found [this function](https://github.com/QubitProducts/cookieman/blob/master/lib/cookieman.js#L49) a lot in flame charts when inspecting performance. By replacing this function with a `cookie.split(';')`, getting a cookie is about 5 to 15 times faster (greatly improving Jolt performance).

I will try to provide a solid benchmark to show the difference in performance but I am sure this method can perform as fast as `cookie.split(';')` and pass all tests, I will take a better look soon.

**Comment by roberttod** [comment]
Closing this issue because actually I need to investigate this further.

**Comment by alanclarke** [comment]
so, split(';') is not what this does, but we could try:

```
cookie.split(/(=.+)/)

or

var i = cookie.indexOf('=')
if (i < 0) return [cookie]
return [cookie.substr(0, i), cookie.substr(i + 1)]

```

**Comment by alanclarke** [comment]
yeah actually split by index is the fastest: http://jsperf.com/split-first-instance/2

**Comment by alanclarke** [comment]
the existing regex is about 73% slower. can't see this being a massive bottleneck though

**Comment by alanclarke** [comment]
Actually i wonder if we could improve performance by pulling out individual cookies with a regex instead of doing ```getCookies()``` (```essentially mapping a document.cookie.split(';')```)

**Comment by alanclarke** [comment]
we should keep an in memory object and flush to cookie a maximum of once per tick. that should solve the cookie perf issues
