### ISSUE TITLE
Set expiry as a length of time

### ISSUE THREAD

**Issue by KwanMan** [QubitProducts/cookieman#14]
99% of the times I set a cookie, the expiry is a specific amount of time from now (e.g. 1 day, 1 year) and currently need to calculate that every time.

`new Date((new Date()).getTime() + (365 * 24 * 60 * 60 * 1000))`

Would be great to have an option to pass in a length of time rather than a date object

Would either be
1/ `options.expiresIn = 365 * 24 * 60 * 60 * 1000` - But this might cause confusion as to which takes precedent if both `option.expires` and `option.expiresIn` is set

2/  if `options.expires` is an integer, treat it as a time period and add it to the current time to get the expiry date - May also cause confusion since passing different types does significantly different things

@alanclarke ?

**Comment by alanclarke** [comment]
Wow that does sound like a pain!

Agree it should probably accept and coerce dates/numbers, and also agree that the type shouldn't change the semantics, will accept a pr to that effect

For the other bit, what if we also make available a little date lib that anyone can use more generally?

Something like:

```js
function now () {
  return new Date().getTime()
}

function plus (val, unit) {
   ... date addition logic, e.g. plus 1 'year', plus 1 'month'
}

function minus (val, unit) {
  return plus(-val, unit)
}

now.plus = plus
now.minus = minus
module exports = now
```

which you could use like so:

```js
var now = require('now')
var ms =  now()
var dayLater = now.plus(1, 'day')
var yearAgo = now.minus(1, 'year')
```

**Comment by alanclarke** [comment]
```js
cm.set('my', 'cookie', { 
   expires: now.plus(1, 'year')
})
```

**Comment by alanclarke** [comment]
but also we make it work with the following:
```js
cm.set('my', 'cookie', { 
   expires: new Date().getTime() + (365 * 24 * 60 * 60 * 1000)
})
```

**Comment by KwanMan** [comment]
Yes, I like the idea of a micro date lib, we do a lot of work that involves manipulating time so will be pretty helpful to have something to deal with that.

I'll PR the timestamp change first and have a think about what else we might want in a date lib
